server:
  port: 8002


mybatis:
  type-aliases-package: cn.cvzhanshi.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: lian0911
    username: root
    driver-class-name: com.mysql.jdbc.Driver
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002

# info配置
info:
  # 项目的名称
  app.name: cvzhanshi-springcloud
  # 公司的名称
  company.name: blog.cvzhanshi.com

